import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [
    {type: 'category', label: 'Start here', items: ['guide/getting-started', 'operations']},
    {type: 'category', label: 'Workflows', items: ['guide/export-unlock', 'guide/validate-serialize', 'guide/errors']},
  ],
  concepts: [
    {type: 'category', label: 'KeyHold foundations', items: ['concepts/document-format', 'concepts/password-crypto', 'concepts/interoperability', 'concepts/security-model']},
  ],
  api: [
    {type: 'category', label: 'TypeScript API', items: [{type: 'autogenerated', dirName: 'api/typescript'}]},
    {type: 'category', label: 'Go API', items: [{type: 'autogenerated', dirName: 'api/go'}]},
  ],
  release: ['release-notes'],
};

export default sidebars;
